account/urls.py
from django.urls import path, include
from . import views


urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
    path('edit/', views.edit, name='edit'),
]

blog/urls.py
from django.urls import path
from . import views as bv

app_name = 'blog'

urlpatterns = [
    path('', bv.all_blogs, name='all_blogs'),
    path('<int:blog_id>/', bv.detail, name='detail'),
]

my_portfolio/urls.py
from django.urls import path
from . import views as pv

app_name = 'project'

urlpatterns = [
    path('', pv.portfolio_projects, name='portfolio_projects'),
    path('<int:project_id>/', pv.project_detail, name='project_detail'),
    
    path('index/', pv.index, name='index')
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from my_portfolio import views as mpv
from blog import views as bv

app_name = 'main'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', mpv.home, name='home'),
    path('project/', include('my_portfolio.urls')),
    path('blog/', include('blog.urls')),

    path('celery/', include('my_portfolio.urls')),

    path('account/', include('account.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/models.py
from django.db import models
from django.conf import settings


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    date_of_birth = models.DateField(blank=True, null=True)
    photo = models.ImageField(upload_to='users/%Y/%m/%d/', blank=True)

    def __str__(self):
        return f'Profile for user {self.user.username}'

blog/models.py
from django.db import models
from time import time
from datetime import datetime


class Blog(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    date = models.DateTimeField(default=datetime.now)

    def __str__(self):
        return self.title

my_portfolio/models.py
from django.db import models
from datetime import datetime


class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    image = models.ImageField(blank=True, upload_to='my_portfolio/img')
    date = models.DateTimeField(default=datetime.now)
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

account/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password',
                               widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password',
                                widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'email')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password2']


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')


class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('date_of_birth', 'photo')

account/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import Profile
from .forms import LoginForm, UserRegistrationForm, UserEditForm, ProfileEditForm
from  my_portfolio.tasks import *


def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request,
                                username=cd['username'],
                                password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponse('Authenticated ' 'successfully')
                else:
                    return HttpResponse('Disabled account')
            else:
                return HttpResponse('Invalid login')
    else:
        form = LoginForm()
    return render(request, 'account/login.html', {'form': form})


@login_required
def dashboard(request):
    return render(request,
                  'account/dashboard.html',
                  {'section': 'dashboard'})


def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            # Create a new user object but avoid saving it yet
            new_user = user_form.save(commit=False)
            # Set the chosen password
            new_user.set_password(
                user_form.cleaned_data['password'])
            # Save the User object
            new_user.save()
            # Create the user profile
            Profile.objects.create(user=new_user)
            send_email_task(new_user)
            return render(request,
                          'account/register_done.html',
                          {'new_user': new_user})
    else:
        user_form = UserRegistrationForm()
    return render(request,
                  'account/register.html',
                  {'user_form': user_form})


@login_required
def edit(request):
    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user,
                                 data=request.POST)
        profile_form = ProfileEditForm(
                                    instance=request.user.profile,
                                    data=request.POST,
                                    files=request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Profile updated successfully')
        else:
            messages.error(request, 'Error updating your profile')
    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.profile)
    return render(request,
                  'account/edit.html',
                  {'user_form': user_form,
                   'profile_form': profile_form})

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog


def all_blogs(request):
    # blogs = Blog.objects.all()
    blogs = Blog.objects.order_by('-date')  # [:10]
    return render(request, 'blog/all_blogs.html', {'blogs': blogs})


def detail(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    return render(request, 'blog/detail.html', {'blog': blog})

my_portfolio/views.py
from django.shortcuts import render, get_object_or_404
from .models import Project
from django.http import HttpResponse
from .tasks import *


def index(request):
    # sleepy.delay(10)
    send_email_task()
    return HttpResponse('<h1>Task is done</h1>')


def home(request):
    return render(request, 'my_portfolio/home.html')


def portfolio_projects(request):
    projects = Project.objects.all()
    return render(request, 'my_portfolio/portfolio_projects.html', {'projects': projects})


def project_detail(request, project_id):
    project = get_object_or_404(Project, pk=project_id)
    return render(request, 'my_portfolio/project_detail.html', {'project': project})

blog/templates/blog/all_blogs.html
{% extends 'my_portfolio/index.html' %}

{% load static %}


{% block content %}
<br>
<div class="container">
    <h2 class="text-center">Blog post</h2>
    <div class="row">

        {% for blog in blogs %}

        <div class="col-md-6">
            <div class="card" style=" margin: 15px 0px 15px 0px;">
                <div class="card-body" style="height: 200px;">
                    <a href="{% url 'blog:detail' blog.id %}"><h4 class="card-title">{{ blog.title }}</h4></a>
                    <p class="card-text">{{ blog.description|striptags|truncatechars:140}}</p>
                    <p class="text-muted card-subtitle mb-2">({{ blog.date|date:'M D Y  H:i' }})</p>
                </div>
            </div>
        </div>

        {% endfor %}

    </div>
</div>

{% endblock %}

blog/templates/blog/detail.html
{% extends 'my_portfolio/index.html' %}

{% load static %}

{% block content %}
<br><br>
<div class="container">
    <h2>{{ blog.title }}</h2>
    <p>{{ blog.description|safe }}</p>
    <a href="{% url 'blog:all_blogs' %}">Back</a>
</div>
{%endblock %}

my_portfolio/templates/my_portfolio/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

    <title>Home page</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="#">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Dropdown
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="#">Action</a></li>
                <li><a class="dropdown-item" href="#">Another action</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="#">Something else here</a></li>
              </ul>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
            </li>
          </ul>
          <form class="d-flex">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        </div>
      </div>
    </nav>

    {% block content %}{% endblock %}





    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js" integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script>
    -->
  </body>
</html>

my_portfolio/templates/my_portfolio/home.html
{% extends 'my_portfolio/index.html' %}

{% load static %}

{% block content %}

<div class="header">
    <div class="team-clean">
        <div class="container">
            <div class="row people">
                <div class="col-md-6 col-lg-6 offset-lg-3 item">
                    <img class="rounded-circle" alt="Owner photo" src="{% static 'my_portfolio/KimVA320_320.jpg' %}">
                    <h3 class="name">Kim Vladimir</h3>
                    <p class="title">Python developer</p>
                    <p class="description">Python, Django, Rest API, Docker, Celery, PostgreSQL, Git, English B1</p>
                    <div class="social">
                        <a href="https://www.linkedin.com/in/-vladimir-kim/"><i class="fa fa-linkedin"></i></a>
                        <a href="https://github.com/B0B82"><i class="fa fa-git"></i></a>
                        <a href="@Kimvladimir_dev"><i class="fa fa-telegram"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

my_portfolio/templates/my_portfolio/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Portfolio Kim Vladimir</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'my_portfolio/styles.min.css' %}">
</head>

<body>
    <!-- Start: Navigation Clean -->
    <nav class="navbar navbar-light navbar-expand-md navigation-clean">
        <div class="container">
            <a class="navbar-brand">Personal portfolio</a>
            <button data-toggle="collapse" class="navbar-toggler" data-target="#navcol-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse"
                id="navcol-1">
                <ul class="nav navbar-nav ml-auto">
                    <li class="nav-item" role="presentation"><a class="nav-link" href="{% url 'home' %}">Home</a></li>
                    <li class="nav-item" role="presentation"></li>
                    <li class="nav-item dropdown show">
                        <a class="dropdown-toggle nav-link" data-toggle="dropdown" aria-expanded="true" href="#">Projects</a>
                        <div class="dropdown-menu" role="menu">
                            <a class="dropdown-item" role="presentation" href="{% url 'project:portfolio_projects' %}">List</a>
                            {% for project in projects %}
                            <a class="dropdown-item" role="presentation" href="{% url 'project:project_detail' project.id %}">{{ project.title }}</a>
                            {% endfor %}
                        </div>
                    </li>
                    <li class="nav-item" role="presentation"><a class="nav-link" href="{% url 'blog:all_blogs' %}">Blog</a></li>
                    <li class="nav-item" role="presentation">

                        {% if request.user.is_authenticated %}
                            <form action="{% url 'logout' %}">
                                <button type="submit" class="btn btn-primary">Logout, {{ request.user }}</button>
                            </form>
                        {% else %}
                            <form action="{% url 'login' %}">
                                <button type="submit" class="btn btn-primary">Log-in</button>
                            </form>
                        {% endif %}

                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- End: Navigation Clean -->
    <br>
    {% block content %}{% endblock %}

    <footer class="text-center">
        <p class="text-center contact">Ukraine Kiev | +38 063 853 27 53 </p>
        <a href = "mailto:kimvlolodymyr1@gmail.com">Send Email</a>
    </footer>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.bundle.min.js"></script>
</body>

</html>

my_portfolio/templates/my_portfolio/portfolio_projects.html
{% extends 'my_portfolio/index.html' %}

{% load static %}

{% block content %}
<br>
<div class="container">
    <h2 class="text-center">Projects</h2>
    <div class="row d-md-flex justify-content-md-center">

        {% for project in projects %}

        <div class="col-md-6">
            <div class="card" style=" margin: 15px 0px 15px 0px;">
                <div class="card-body">
                    <img src="{% if project.image %}{{ project.image.url }}{% else %}{% static 'my_portfolio/no_image.jpg' %}{% endif %}" class="d-none d-md-block d-lg-block" style="float:right;width:160px;height:200px;">
                    <a href="{% url 'project:project_detail' project.id %}"><h4 class="card-title">{{ project.title }}</h4></a>
                    <p class="card-text">{{ project.description|striptags|truncatechars:150}}</p>
                    <p class="text-muted card-subtitle mb-2">({{ project.date|date:'M D Y  H:i' }})</p>
                </div>
            </div>
        </div>

        {% endfor %}
    </div>
</div>

{% endblock %}

my_portfolio/templates/my_portfolio/project_detail.html
{% extends 'my_portfolio/index.html' %}

{% load static %}

{% block content %}
<br><br>
<div class="container">
    <h2>{{ project.title }}</h2>
    <p>{{ project.description|safe }}</p>
    <a href="{% url 'project:portfolio_projects' %}">Back</a>
</div>
{%endblock %}